nav_planning_console:
  ros__parameters:
    web_host: 127.0.0.1
    web_port: 8080
    map_topic: /map
    global_frame: map
    base_frame: base_link
    planner_action_name: compute_path_to_pose
    navigator_action_name: navigate_to_pose
    manual_cmd_topic: cmd_vel_manual
    manual_control_enabled: true
    manual_max_linear_velocity: 0.25
    manual_max_angular_velocity: 0.50
    person_tracking_control_enabled: true
    person_tracking_node_name: person_tracking
    person_tracking_image_topic: /zed/zed_node/rgb/color/rect/image/compressed
    person_tracking_engine_path: /home/jetson-nano-x1/Documents/B_Cubed/models/yolo11n.engine
    person_tracking_show_window: false
    person_tracking_publish_annotated_image: true
    person_tracking_detection_topic: /person_tracking/detections
    person_tracking_annotated_image_topic: /person_tracking/annotated_image/compressed
    person_tracking_confidence_threshold: 0.4
    person_tracking_nms_threshold: 0.45
    planner_id: ""
    planner_server_timeout_sec: 2.0
    navigator_server_timeout_sec: 2.0
    planning_timeout_sec: 10.0
    navigation_plane_z: 0.0
    pose_update_period_sec: 0.2
    start_pose_rescue_enabled: true
    start_pose_rescue_radius: 0.50
    start_pose_rescue_clearance: 0.25
    start_pose_occupied_threshold: 65
    start_pose_unknown_is_occupied: false
